# This is boilerplate:
# Still need to determine if Docker is even worth using.

version: "3"
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container
    build: ./server
    ports:
      - "3000:3000"
    container_name: backend-docker
    restart: always
    links:
      - db
